### ISSUE TITLE
Problem using SOFA with `SoftRobots` & `STLIB` & `SofaPython3` plugins

### ISSUE THREAD

**Issue by Sihtralad** [sofa-framework/sofa#2754]
Greetings,

I have built SOFA v21.12 without any error massages, on Ubuntu 18.04. And it works fine without plugins. However when I try to run examples for SoftRobots, I encounter the same problems as previously described is following topics, also tried the solutions that is described there. (Also tried to build on Ubuntu 20.04 but the result is the same)

https://www.sofa-framework.org/community/forum/topic/error-couldnt-import-objects-from-stlib3-physics-rigid/

https://www.sofa-framework.org/community/forum/topic/issues-with-running-examples-on-sofa_v20-12-02_defrost_linux/

Has this problem been solved?

Moreover, my colleague also built SOFA and the plugins on Ubuntu 20.04, then sent me the built version of his. I have re-installed Ubuntu 20.04 with his user name, and surprisingly the plugins worked without any errors. Therefore, I am assuming there might be a mistake while I use Cmake. However, as me and my colleague discussed, we have followed exactly the same method but the results were different.

I get the following error massage when I try to run SOFA with my build:

`[ERROR]   [SofaPython3::SceneLoader] Unable to completely load the scene from file '....path/to/file.../SoftRobots/docs/tutorials/FirstSteps/details/sofapython3/step4.py3scn'.  
Python exception:   
  ImportError: cannot import name 'Floor' from 'stlib3.physics.rigid' (/....path/to/file...../sofa/build/lib/python3/site-packages/stlib3/physics/rigid/__init__.py)

At:
  step4.py3scn(2): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(843): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(702): _load
  /usr/lib/python3.8/imp.py(171): load_source
  /usr/lib/python3.8/imp.py(234): load_module
  <string>(3): <module>
`

**Comment by damienmarchal** [comment]
Hi @Sihtralad, 

thank you for reporting the issue. 

We made some fixes for the RoboSoft conference
But in general we don't backport the fixes to old releases (the 21.12 is a past release). 

Could you confirm this problem is still there with the master branches of Sofa+STLIB+SoftRobot ?
