### PR TITLE
[SofaCUDA] Make CudaConstantForceField compatible with CudaRigid types

### LINKED ISSUE #2575: [SofaCUDA] Make CudaConstantForceField compatible with CudaRigid types
CudaConstantForceField is introduced in https://github.com/sofa-framework/sofa/pull/2557.
ConstantForceField supports Rigid2Types and Rigid3Types. To have the same support on CUDA, CudaConstantForceField must support CudaRigid2Types and CudaRigid3Types. Currently, those types lead to compilation errors. It must be fixed

### PR DESCRIPTION
**Pull request by ChangjingLiu**
1. Make CudaConstantForceField compatible with CudaRigid types CudaRigid3Types and CudaRigid2Types

fix #2575 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by ChangjingLiu** [comment]
Refer to PR #2575

File: applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp [hunk 1]
```diff
@@ -24,18 +24,27 @@
 #include <sofa/core/behavior/ForceField.inl>
 #include <sofa/gpu/cuda/CudaTypes.h>
 
-namespace sofa::gpu::cuda
+namespace sofa::component::mechanicalload
```
Comment (epernod) [inline applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp]: the namespace sofa::gpu::cuda was correct

File: applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp [hunk 2]
```diff
@@ -24,18 +24,27 @@
...
     int ConstantForceFieldCudaClass = core::RegisterObject("Constant forces applied to given degrees of freedom")
         .add< ConstantForceField<CudaVec3Types> >()
         .add< ConstantForceField<CudaVec2Types> >()
         .add< ConstantForceField<CudaVec1Types> >()
         .add< ConstantForceField<CudaVec6Types> >()
+        .add< ConstantForceField<CudaRigid3Types> >()
+        .add< ConstantForceField<CudaRigid2Types> >()
     ;
-} // namespace sofa::gpu::cuda
+} // namespace sofa::component::mechanicalload
```
Comment (epernod) [inline applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp]: same as above

File: applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp [hunk 3]
```diff
@@ -24,18 +24,27 @@
...
 {
-    using namespace sofa::component::mechanicalload;
+
+    using namespace sofa::gpu::cuda;
+
+    template <> SOFA_GPU_CUDA_API
+    SReal ConstantForceField<CudaRigid3Types>::getPotentialEnergy(const core::MechanicalParams*, const DataVecCoord& ) const { return 0; }
+    template <> SOFA_GPU_CUDA_API
+    SReal ConstantForceField<CudaRigid2Types>::getPotentialEnergy(const core::MechanicalParams*, const DataVecCoord& ) const { return 0; }
+
```
Comment (epernod) [inline applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaConstantForceField.cpp]: could you move this code below after line 50

File: applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h [hunk 4]
```diff
@@ -634,6 +638,163 @@ inline const char* CudaRigid3fTypes::Name()
...
+    static const char* Name();
+
+    typedef CudaVector<Coord> VecCoord;
+    typedef CudaVector<Deriv> VecDeriv;
+    typedef CudaVector<Real> VecReal;
+
+    typedef defaulttype::MapMapSparseMatrix<Deriv> MatrixDeriv;
+
+    template<typename T>
+    static void set(Coord& c, T x, T y, T)
```
Comment (epernod) [inline applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h:683]: I never used rigid2Types so I'm not sure of the API but it would make sens to me to add ```set```, ```get``` and ```add``` methods below with a version with only (T& x, T& y , without the z variable which is then ignored.

**Review by epernod — CHANGES_REQUESTED** [review]
Just a few comment from my side. I didn't check the math. I let that to a Phd 🤣

File: applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h (hunk 4 above)
Comment (ChangjingLiu) [reply applications/plugins/SofaCUDA/sofa/gpu/cuda/CudaTypes.h:683]: Sorry, I'm not familiar with GitHub, and I accidentally clicked the **request review** again.....😢
