### ISSUE TITLE
CGALPlugin compilation error @Refine2DMesh

### ISSUE THREAD

**Issue by omarboukhris** [sofa-framework/sofa#1474]
CGALPlugin does not compile with CGAL 5.02.
```c++
for (
    typename CDT::Vertices_in_constraint_iterator it =   
    cdt.vertices_in_constraint_begin(va,vb), succ = it, itend =
    cdt.vertices_in_constraint_end(va,vb); ++succ != itend; ++it)
```

______________________________________________________

Suggested labels:

**Comment by hugtalbot** [comment]
Thanks @omarboukhris 
What is the status of this? Are you taking a look at it? Cheers !

**Comment by hugtalbot** [comment]
What's up on this topic @omarboukhris ? Could you handle it?

**Comment by omarboukhris** [comment]
> What's up on this topic @omarboukhris ? Could you handle it?

I'm overwhelmed right now with the coming experiments, 
I'll try to look into it as soon as I can
