### PR TITLE
[all] Unused include directive

### PR DESCRIPTION
**Pull request by alxbilger**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
> CI cries :
> 
> ```
> MechanicalMatrixMapper.h:50:27: error: no matching function for call to 'sofa::simulation::BaseMechanicalVisitor::BaseMechanicalVisitor(const sofa::core::ConstraintParams*&)'
>    50 |         , cparams(_cparams)
>       |                           ^
> ```

@hugtalbot Thank you. I suspect this will be fixed by https://github.com/sofa-framework/sofa/pull/2481.

**Comment by fredroy** [comment]
One small thing, should we mark this PR as breaking? 
From my experience (🥱), a lot of people don't really include what they use, so it could happen that a seemingly useless include in one could be useful further, in their plugin or whatever. I know this is really a bad practice from their part but still, people complain even if it is their fault 🤪.

**Comment by alxbilger** [comment]
@fredroy Sure!

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Review by fredroy — APPROVED** [review]
