### ISSUE TITLE
[SofaCUDA] Make CudaConstantForceField compatible with CudaRigid types

### ISSUE THREAD

**Issue by alxbilger** [sofa-framework/sofa#2575]
CudaConstantForceField is introduced in https://github.com/sofa-framework/sofa/pull/2557.
ConstantForceField supports Rigid2Types and Rigid3Types. To have the same support on CUDA, CudaConstantForceField must support CudaRigid2Types and CudaRigid3Types. Currently, those types lead to compilation errors. It must be fixed
