### PR TITLE
[CGALPlugin] Fix compilation for CGal version > 5

### LINKED ISSUE #1474: CGALPlugin compilation error @Refine2DMesh
CGALPlugin does not compile with CGAL 5.02.
```c++
for (
    typename CDT::Vertices_in_constraint_iterator it =   
    cdt.vertices_in_constraint_begin(va,vb), succ = it, itend =
    cdt.vertices_in_constraint_end(va,vb); ++succ != itend; ++it)
```

______________________________________________________

Suggested labels:

### PR DESCRIPTION
**Pull request by courtecuisse**
Fix compilation of cgal (include problem)

Comment the part of the code that is not compiling with cgal 5

Fix #1474 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

File: applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl [hunk 1]
```diff
@@ -351,7 +351,7 @@ namespace cgal
 				}
 			}
 		}
-		
+#endif
```
Comment (fredroy) [inline applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl:309]: Disabling code for everybody because it is not compiling with CGAL5  is not really nice 🧨 (CGAL 4.X guys wont appreciate)
If not fixing, then at least enclose the disabled code with check on CGAL version + a pragma message telling that Refine2DMesh is not working anymore with CGAL5

**Comment by fredroy** [comment]
Well done to fix errors introduced in recent previous merge ( not detected in the reviews 😭)

**Review by fredroy — CHANGES_REQUESTED** [review]

File: applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl [hunk 2]
```diff
@@ -125,7 +125,7 @@ void DecimateMesh<DataTypes>::doUpdate()
     }
     else
     {
-        msg_erro() << "You must add a stop condition using either targetedNumberOfEdges or targetedRatioOfEdges" ;
+        msg_error(this) << "You must add a stop condition using either targetedNumberOfEdges or targetedRatioOfEdges" ;
```
Comment (damienmarchal) [inline applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl]: The "this" is not needed. 
msg_error() is equivalent.

Comment (courtecuisse) [reply applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl]: Hi, I think I had an error without adding "this". I don't know if it was related to an include problem. Maybe you are wright it's not necessary. Thx :)

File: applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl (hunk 1 above)
Comment (courtecuisse) [reply applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl:309]: Of course ! What is the macro ? 
According to me this file can be completely removed with cgal 5 because the component will exists but with an incorrect behavior. Who need this component ?

File: applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl (hunk 2 above)
Comment (epernod) [reply applications/plugins/CGALPlugin/src/CGALPlugin/DecimateMesh.inl]: no I think, you just got a compilation error because it was msg_erro   (r missing)

File: applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl (hunk 1 above)
Comment (epernod) [reply applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl:309]: I fixed this code for CGAL > 5, but I cannot push in this branch.

**Comment by epernod** [comment]
> 
> 
> Thanks @courtecuisse for fixing the issue !! Great job 👍
> 
> Fix #1474 @omarboukhris

I'm not sure the keyword works in a comment (https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

**Review by hugtalbot — APPROVED** [review]

File: applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl [hunk 3]
```diff
@@ -291,15 +292,22 @@ namespace cgal
...
+
+            for (typename CDT::Vertices_in_constraint_iterator it =
+                cdt.vertices_in_constraint_begin(cid), succ = it, itend =
+                cdt.vertices_in_constraint_end(cid); ++succ != itend; ++it)
+#else
+            for (typename CDT::Vertices_in_constraint_iterator it =
+                cdt.vertices_in_constraint_begin(va, vb), succ = it, itend =
+                cdt.vertices_in_constraint_end(va, vb); ++succ != itend; ++it)
+#endif
+            {
```
Comment (fredroy) [inline applications/plugins/CGALPlugin/src/CGALPlugin/Refine2DMesh.inl:310]: Weird indentation 😬

**Review by fredroy — APPROVED** [review]
